[package]
name = "basecoat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
tonic = "0.7.1"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
protobuf = "2.27.1"

[build-dependencies]
tonic-build = "0.7.0"
